#!/bin/bash
if [[ $1 == 'start' ]]; then
    mongod --fork --config ./mongod.conf
	echo 'Anipet db is up'

elif [[ $1 == 'stop' ]]; then
    kill -2 `pgrep mongo`
    echo 'Anipet db is down'

elif [[ $1 == 'wipe' ]]; then
    mongorestore --drop --gzip --noIndexRestore --archive=dump/MinimalAnipet.gz
fi
