#!/bin/bash
if [[ $1 == 'start' ]]; then
    mongod --fork --config ./mongod.conf
	echo 'Anipet db is up'

elif [[ $1 == 'stop' ]]; then
    kill -2 `pgrep mongo`
    echo 'Anipet db is down'

elif [[ $1 == 'wipe' ]]; then
    mongorestore --drop --gzip --archive=dump/EmptyAnipet.gz
    echo 'Anipet db got wiped and refreshed'

elif [[ $1 == 'restore' ]]; then
    mongorestore --drop --gzip --archive=dump/MinimalAnipet.gz
    echo 'Anipet db got restored'

elif [[ $1 == 'dump' ]]; then
    mongodump --db Anipet --gzip --archive > dump/MinimalAnipet.gz
    echo 'New db dump is ready to be commited'

fi
